name: "preflight-configuration"
description: "Installs Terragrunt and configures AWS secrets"
inputs:
  role-to-assume:
    required: true
    description: AWS role to assume to STS creds generation.
runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v1.1.0
      with:
        terragrunt_version: 0.36.7
    
    - name: Configure AWS credentials from istio account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: us-east-1

    - name: Interact with Terragrunt
      run: terragrunt --version
      shell: bash

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.1
